name: flutter_weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.1.0
  bloc: ^7.0.0

  equatable: ^2.0.3
  rxdart: ^0.26.0
  http: ^0.13.0
  lottie: ^1.1.0
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Wetherium"

flutter_icons:
  android: true
  image_path: "assets/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/weather.json
    - assets/bg.jpg
    - assets/splash.png
